version: '3.8'

services:
  # Node.js + React Application
  app:
    build:
      context: ..
      dockerfile: ./simplified-docker/Dockerfile.simplified
      target: production
    container_name: priority-poll-app
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=5000
      # Replace this with your local PostgreSQL connection string
      - DATABASE_URL=postgres://localhost:5432/priority_poll_db
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
      - ./.env:/app/.env
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3