version: '3'

services:
  app:
    build: 
      context: ../
      dockerfile: ./deploy/Dockerfile
    container_name: priority-poll
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=5000
      # Important: Update this to point to your local PostgreSQL
      - DATABASE_URL=postgres://host.docker.internal:5432/priority_poll_db
    restart: unless-stopped